### ISSUE TITLE
Error: Cannot find module './src'

### ISSUE THREAD

**Issue by AverageHelper** [lucasgmagalhaes/corde#572]
**Describe the bug**
When I try to run corde, the command fails saying it cannot find one of its internal modules. './src'.

**To Reproduce**
1. Run `corde -c corde.json`
2. See error

**Expected behavior**
I expect the tests to run.

**Screenshots**
![Screen Shot 2021-03-20 at 12 02 50 PM](https://user-images.githubusercontent.com/1500092/111881139-cb013e00-8974-11eb-93c8-ab0c067a3cfa.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Terminal: zsh
 - Corde version: 2.0.1

**Additional context**
It seems that the bundle from NPM does come with a /src folder, but this is buried under /lib. Is it possible that a rogue import caused the TS compiler to place everything one layer too deep?

**Comment by AverageHelper** [comment]
If I go into node_modules/corde and change a couple of lines, everything works fine:

```JavaScript
// index.js
export * from "./lib";

import corde from "./src"; // This should import from "./lib";
export default corde;
```

and the same in the corresponding index.d.ts filel

**Comment by lucasgmagalhaes** [comment]
I got it! Thank you for the help @AverageHelper. Going to fix it.

**Comment by lucasgmagalhaes** [comment]
Hey @AverageHelper, check the version 2.0.2. The problem should had been fixed.
(I closed unintentionally the issue. Be free to check if it's working)

**Comment by lucasgmagalhaes** [comment]
I'm also working in a new UI for the CLI report, so, hold on for just some more time 🙂

**Comment by AverageHelper** [comment]
It worked! Thank you

**Comment by lucasgmagalhaes** [comment]
Closing this issue then.
