### ISSUE TITLE
Allow to assert that a message was sent in another channel

### ISSUE THREAD

**Issue by AverageHelper** [lucasgmagalhaes/corde#585]
I'm working on a queue bot that acts on a submission command by sending a specially formatted message to a predetermined channel and sending a response to the command sender in the original channel. I can assert easily enough that the response comes through, but there doesn't seem to be a good way of checking the other channel for new messages by the Corde bot.

The syntax might look something like this:
```TypeScript
expect("sr something").toReturn("Public Response"); // checks same channel as command
expect("sr something").toReturnInChannel("Secret Response", "channel_id"); // checks the given channel
```

Since I'd like to assert as well that the response happened in both channels from the same command, a composable assertion API might be useful. Perhaps something like:
```TypeScript
expect("sr something").toHaveResult(
  expect.toReturn("Public Response"), // checks same channel as command
  expect.toReturnInChannel("Secret Response", "channel_id") // checks the given channel
);
```
(Based on Jest's [`expect`](https://jestjs.io/docs/expect) matchers API)

EDIT: Fixed a misspelling of an existing API function to compare with the proposed one. (`toReturn` is the one for same-channel assertion)

**Comment by lucasgmagalhaes** [comment]
hmm, that look pretty cool. I wasn't thinking about verify things in another channels, but that syntax that you purpose is really nice.
I will start to working on this, but the second sugestion is a little more complicated, so it will take more time to be done.

Anyway, thank you so much for the sugestion!

**Comment by lucasgmagalhaes** [comment]
@AverageHelper I added the features that you suggested. They are in version `3.1.0-beta.1` I still have to make some more tests to confirm that it's all ok, but the use case that you gave in the example is working. Please take a look.

**Comment by AverageHelper** [comment]
I've looked over the code. Very nice!  I'm excited to give this a try!

**Comment by lucasgmagalhaes** [comment]
As the feature was released. I'm going to close this issue. Feel free to reopen it or create a new one if needed.
