### ISSUE TITLE
Window newline characters cannot understand by Unix based System

### ISSUE THREAD

**Issue by GarfDev** [lucasgmagalhaes/corde#641]
**Describe the bug**
Window newline characters cannot understand by Unix based System

**To Reproduce**
1. Install corde with yarn
2. Run `yarn corde --init` command

**Expected behavior**
corde config file created

**Screenshots**
[Image](https://i.imgur.com/yB8EiWp.png)

**Desktop (please complete the following information):**
 - OS: Macos
 - Terminal: iterm2 
  - Corde version 3.1.0

**Additional context**
https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo

**Comment by GarfDev** [comment]
Working on a fix

**Comment by GarfDev** [comment]
So I found the problem, it inside `bin/corde` file, the end-line type of that file currently set as `CSLF`, so on mac (and Linux distro I think) using "LF". solution can be found in  the second answer here:
`https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo`

**Comment by lucasgmagalhaes** [comment]
Hi @GarfDev. I'm sorry about that. I'm going to fix it today.

**Comment by lucasgmagalhaes** [comment]
@GarfDev take a look in v3.1.2,

**Comment by samhwang** [comment]
Hi @lucasgmagalhaes , I think this problem still persists in the newest version (I just installed corde version 4.0.1) and it still encountered the same issue. And I've tested this under 3 different scenarios: in an Alpine Linux container, on an Ubuntu machine and on a MacOS machine.

**Scenario 1: In an Alpine Linux container**

![Screenshot from 2021-05-19 14-31-58](https://user-images.githubusercontent.com/4188758/118756786-00f86b00-b8af-11eb-9a79-f013a6525881.png)

**Scenario 2: In an Ubuntu machine**
![Screenshot from 2021-05-19 14-37-41](https://user-images.githubusercontent.com/4188758/118757250-115d1580-b8b0-11eb-933e-483a4ca3d01a.png)

And these 2 can be fixed just by changing the the `/bin/corde` into using LF endings. Going forward I'd suggest having some linting/formatting rules that change all these into using LF consistently, so for newer releases we won't have to revisit this :D

**Comment by lucasgmagalhaes** [comment]
Hi @samhwang. Sorry about that. Yeah, there is an `.editorconfig` with LF rule, and I don't understand why it persist to format as CRLF. I made some research, and I think that can force the usage of LF by setting it in `.gitattribute`.

Anyway, sorry about that.
